#!/usr/bin/env pwsh
# ============================================================================
# PDF Autofillr - Automated Setup Script (Windows/PowerShell)
# ============================================================================
# This script automatically sets up the entire project on Windows
# Usage: .\setup.ps1

param(
    [switch]$SkipOllama,
    [switch]$SkipVenv,
    [string]$Model = "llama3.1"
)

$ErrorActionPreference = "Stop"

Write-Host "🚀 PDF Autofillr - Automated Setup" -ForegroundColor Cyan
Write-Host "==================================`n" -ForegroundColor Cyan

# ============================================================================
# 1. Check Prerequisites
# ============================================================================
Write-Host "📋 Checking prerequisites..." -ForegroundColor Yellow

# Check Python
try {
    $pythonVersion = python --version 2>&1
    Write-Host "✅ Python found: $pythonVersion" -ForegroundColor Green
} catch {
    Write-Host "❌ Python not found. Please install Python 3.8+ from https://www.python.org/" -ForegroundColor Red
    exit 1
}

# Check pip
try {
    $pipVersion = pip --version 2>&1
    Write-Host "✅ pip found: $pipVersion" -ForegroundColor Green
} catch {
    Write-Host "❌ pip not found. Please install pip." -ForegroundColor Red
    exit 1
}

# ============================================================================
# 2. Setup Ollama (Optional)
# ============================================================================
if (-not $SkipOllama) {
    Write-Host "`n🤖 Setting up Ollama (Open Source LLM)..." -ForegroundColor Yellow
    
    # Check if Ollama is installed
    try {
        $ollamaVersion = ollama --version 2>&1
        Write-Host "✅ Ollama found: $ollamaVersion" -ForegroundColor Green
        
        # Pull the model
        Write-Host "📥 Pulling model: $Model..." -ForegroundColor Yellow
        ollama pull $Model
        Write-Host "✅ Model downloaded successfully!" -ForegroundColor Green
        
    } catch {
        Write-Host "⚠️  Ollama not found." -ForegroundColor Yellow
        Write-Host "   Would you like to:" -ForegroundColor Yellow
        Write-Host "   1. Install Ollama now (will open browser)" -ForegroundColor White
        Write-Host "   2. Skip Ollama (you can use OpenAI API instead)" -ForegroundColor White
        $choice = Read-Host "   Enter choice (1 or 2)"
        
        if ($choice -eq "1") {
            Start-Process "https://ollama.ai/download"
            Write-Host "`n⚠️  Please install Ollama and run this script again." -ForegroundColor Yellow
            exit 0
        } else {
            Write-Host "⚠️  Skipping Ollama setup. You'll need to configure OpenAI API key manually." -ForegroundColor Yellow
        }
    }
} else {
    Write-Host "`n⏭️  Skipping Ollama setup (--SkipOllama flag)" -ForegroundColor Yellow
}

# ============================================================================
# 3. Create Directory Structure
# ============================================================================
Write-Host "`n📁 Creating directory structure..." -ForegroundColor Yellow

$dirs = @(
    "data/modules/mapper_sample/cache",
    "data/modules/mapper_sample/input",
    "data/modules/mapper_sample/output",
    "data/modules/mapper_sample/tmp",
    "data/modules/mapper_sample/rag-data"
)

foreach ($dir in $dirs) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}
Write-Host "✅ Directories created" -ForegroundColor Green

# ============================================================================
# 5. Configure Mapper Module
# ============================================================================
Write-Host "`n⚙️  Configuring mapper module..." -ForegroundColor Yellow

Set-Location "modules/mapper"

# Create .env based on LLM choice
if ($llmChoice -eq "1") {
    # Ollama configuration
    $envContent = @"
# PDF Mapper Module - Environment Variables
# Auto-generated by setup script

CLOUD_PROVIDER=local

# LLM Configuration - Using Ollama (Open Source)
LLM_MODEL=ollama/$Model
LLM_TEMPERATURE=0.0
LLM_MAX_TOKENS=4096
LLM_TIMEOUT=120
LLM_MAX_RETRIES=3

# Ollama Configuration
OLLAMA_API_BASE=http://localhost:11434

# Logging
LOG_LEVEL=INFO
"@
} elseif ($llmChoice -eq "2") {
    # OpenAI configuration
    $apiKeyValue = if ($openaiKey) { $openaiKey } else { "your-openai-api-key-here" }
    $envContent = @"
# PDF Mapper Module - Environment Variables
# Auto-generated by setup script

CLOUD_PROVIDER=local

# 6LM Configuration - Using OpenAI
LLM_MODEL=$Model
LLM_TEMPERATURE=0.0
LLM_MAX_TOKENS=4096
LLM_TIMEOUT=120
LLM_MAX_RETRIES=3

# OpenAI API Key
OPENAI_API_KEY=$apiKeyValue

# Logging
LOG_LEVEL=INFO
"@
} elseif ($llmChoice -eq "3") {
    # Claude configuration
    $apiKeyValue = if ($anthropicKey) { $anthropicKey } else { "your-anthropic-api-key-here" }
    $envContent = @"
# PDF Mapper Module - Environment Variables
# Auto-generated by setup script

CLOUD_PROVIDER=local

# LLM Configuration - Using Claude/Anthropic
LLM_MODEL=$Model
LLM_TEMPERATURE=0.0
LLM_MAX_TOKENS=4096
LLM_TIMEOUT=120
LLM_MAX_RETRIES=3

# Anthropic API Key
ANTHROPIC_API_KEY=$apiKeyValue

# Logging
LOG_LEVEL=INFO
"@
} else {
    # Default/manual configuration
    $envContent = @"
# PDF Mapper Module - Environment Variables
# Auto-generated by setup script - REQUIRES MANUAL CONFIGURATION

CLOUD_PROVIDER=local

# LLM Configuration - UPDATE THIS!
LLM_MODEL=gpt-4o
LLM_TEMPERATURE=0.0
LLM_MAX_TOKENS=4096
LLM_TIMEOUT=120
LLM_MAX_RETRIES=3

# Add your API key here:
# For OpenAI:
# OPENAI_API_KEY=sk-your-key-here

# For Claude:
# ANTHROPIC_API_KEY=sk-ant-your-key-here

# For Ollama (local):
# LLM_MODEL=ollama/llama3.1
# OLLAMA_API_BASE=http://localhost:11434

# Logging
LOG_LEVEL=INFO
"@
}

$envContent | Out-File -FilePath ".env" -Encoding UTF8
Write-Host "✅ .env file configured" -ForegroundColor Green

# ============================================================================
# 5. Install Python Dependencies
# ============================================================================
Write-Host "`n📦 Installing Python dependencies..." -ForegroundColor Yellow

Write-Host "   Installing core requirements..." -ForegroundColor Gray
pip install -r requirements.txt -q

Write-Host "   Installing API server requirements..." -ForegroundColor Gray
pip install -r requirements-api.txt -q

Write-Host "✅ Dependencies installed" -ForegroundColor Green

# ============================================================================
# 7. Install SDK (Optional)
# ============================================================================
Write-Host "`n🔧 Installing Python SDK..." -ForegroundColor Yellow
Set-Location "../../sdks/python"

# Create SDK .env
$sdkEnvContent = @"
# PDF Autofiller SDK Configuration
PDF_AUTOFILLER_API_URL=http://localhost:8000
PDF_AUTOFILLER_API_KEY=
PDF_AUTOFILLER_USER_ID=1
PDF_AUTOFILLER_PDF_DOC_ID=100
"@

$sdkEnvContent | Out-File -FilePath ".env" -Encoding UTF8

pip install -e . -q
Write-Host "✅ SDK installed" -ForegroundColor Green

# ============================================================================
# 8. Test Configuration
# ============================================================================
Set-Location "../.."
Write-Host "`n🧪 Testing configuration..." -ForegroundColor Yellow

try {
    python -c "from modules.mapper.src.core.config import GlobalConfig; print('Config loaded successfully')" 2>&1 | Out-Null
    Write-Host "✅ Configuration valid" -ForegroundColor Green
} catch {
    Write-Host "⚠️  Configuration test failed (non-critical)" -ForegroundColor Yellow
}

# ============================================================================
# Setup Complete
# ============================================================================
Write-Host "`n" + "="*60 -ForegroundColor Green
Write-Host "✅ Setup Complete!" -ForegroundColor Green
Write-Host "="*60 -ForegroundColor Green

Write-Host "`n📝 Next Steps:" -ForegroundColor Cyan
Write-Host "   1. Start the server:" -ForegroundColor White
Write-Host "      .\start.ps1" -ForegroundColor Yellow
Write-Host "`n   2. Or manually:" -ForegroundColor White
Write-Host "      cd modules/mapper" -ForegroundColor Yellow
Write-Host "      python api_server.py" -ForegroundColor Yellow
Write-Host "`n   3. Test the API:" -ForegroundColor White
Write-Host "      curl http://localhost:8000/health" -ForegroundColor Yellow

if ($venvChoice -eq "1") {
    Write-Host "`n💡 Virtual Environment:" -ForegroundColor Cyan
    Write-Host "   To reactivate later, run:" -ForegroundColor White
    Write-Host "      venv\Scripts\Activate.ps1" -ForegroundColor Yellow
}

if ($llmChoice -eq "2" -and [string]::IsNullOrWhiteSpace($openaiKey)) {
    Write-Host "`n⚠️  Remember: Add your OpenAI API key" -ForegroundColor Yellow
    Write-Host "   Edit modules/mapper/.env and add: OPENAI_API_KEY=sk-..." -ForegroundColor Yellow
} elseif ($llmChoice -eq "3" -and [string]::IsNullOrWhiteSpace($anthropicKey)) {
    Write-Host "`n⚠️  Remember: Add your Anthropic API key" -ForegroundColor Yellow
    Write-Host "   Edit modules/mapper/.env and add: ANTHROPIC_API_KEY=sk-ant-..." -ForegroundColor Yellow
} elseif ($SkipOllama) {
    Write-Host "`n⚠️  Remember: You skipped LLM setup." -ForegroundColor Yellow
    Write-Host "   Update modules/mapper/.env with your API key" -ForegroundColor Yellow
}

Write-Host "`n📖 Documentation:" -ForegroundColor Cyan
Write-Host "   - Setup Guide: modules/mapper/SETUP_GUIDE.md" -ForegroundColor White
Write-Host "   - Quick Ref: QUICK_REFERENCE.md" -ForegroundColor White
Write-Host "   - Examples: examples/QUICK_START.md" -ForegroundColor White

Write-Host "`n🎉 Happy coding!" -ForegroundColor Green
