##############################################################################
# modules/local/main.tf
# Generates .env.local + docker-compose.local.yml for local development.
#
# LocalStack mocks:  STATIC_BUCKET, OUTPUT_BUCKET, PROD_BUCKET
# The FILL_PDF_LAMBDA_URL points at the real downstream Lambda (or a mock).
# PyMuPDF / OpenAI calls go out to the real internet.
##############################################################################

terraform {
  required_providers {
    local = { source = "hashicorp/local"; version = "~> 2.0" }
  }
}

resource "local_file" "env" {
  filename        = "${path.root}/.env.local"
  file_permission = "0600"

  content = <<-ENV
    # ── Generated by Terraform (modules/local) — DO NOT COMMIT ──────────────

    # ── S3 (LocalStack) ──────────────────────────────────────────────────────
    STATIC_BUCKET=${var.static_bucket_name}
    OUTPUT_BUCKET=${var.output_bucket_name}
    PROD_BUCKET=${var.prod_bucket_name}
    AWS_DEFAULT_REGION=us-east-1
    AWS_ACCESS_KEY_ID=test
    AWS_SECRET_ACCESS_KEY=test
    AWS_ENDPOINT_URL=http://localstack:4566

    # ── Downstream fill-pdf Lambda ────────────────────────────────────────────
    # Point at the real URL or a local mock (e.g. another docker service on :9001)
    FILL_PDF_LAMBDA_URL=${var.fill_pdf_lambda_url}
    PDF_API_KEY=${var.pdf_api_key}

    # ── Backend ───────────────────────────────────────────────────────────────
    BACKEND_URL=${var.backend_url}

    # ── Auth ──────────────────────────────────────────────────────────────────
    AUTH_TOKEN=${var.auth_token}

    # ── OpenAI ────────────────────────────────────────────────────────────────
    OPENAI_API_KEY=${var.openai_api_key}

    # ── Teams (leave blank to skip notifications locally) ─────────────────────
    TEAMS_WEBHOOK_URL=${var.teams_webhook_url}

    # ── Runtime ───────────────────────────────────────────────────────────────
    PYTHONUNBUFFERED=1
  ENV
}

resource "local_file" "docker_compose" {
  filename = "${path.root}/docker-compose.local.yml"

  content = <<-COMPOSE
    # Generated by Terraform — local dev environment for doc-upload-lambda
    version: "3.9"

    services:

      # ── LocalStack: mocks S3 ─────────────────────────────────────────────────
      localstack:
        image: localstack/localstack:3
        ports:
          - "4566:4566"
        environment:
          - SERVICES=s3
          - DEFAULT_REGION=us-east-1
        volumes:
          - localstack_data:/var/lib/localstack
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
          interval: 10s
          timeout: 5s
          retries: 5

      # ── Bucket bootstrap ──────────────────────────────────────────────────────
      # Creates STATIC_BUCKET, OUTPUT_BUCKET, PROD_BUCKET in LocalStack
      # Also uploads a stub form_keys.json schema so Lambda can load it
      bucket-init:
        image: amazon/aws-cli:latest
        depends_on:
          localstack:
            condition: service_healthy
        environment:
          - AWS_ACCESS_KEY_ID=test
          - AWS_SECRET_ACCESS_KEY=test
          - AWS_DEFAULT_REGION=us-east-1
        volumes:
          - ./test-data:/test-data   # put test PDFs + form_keys.json here
        entrypoint: ["/bin/sh", "-c"]
        command:
          - |
            EP="--endpoint-url=http://localstack:4566"
            aws $$EP s3 mb s3://${var.static_bucket_name} || true
            aws $$EP s3 mb s3://${var.output_bucket_name} || true
            aws $$EP s3 mb s3://${var.prod_bucket_name} || true

            # Upload schema if present
            if [ -f /test-data/form_keys.json ]; then
              aws $$EP s3 cp /test-data/form_keys.json \
                s3://${var.static_bucket_name}/config/form_keys.json
              echo "✅ Schema uploaded"
            else
              echo "⚠️  No form_keys.json in ./test-data — upload manually"
            fi

            echo "✅ Buckets ready"

      # ── Doc Upload Lambda ──────────────────────────────────────────────────
      # Runs with Lambda Runtime Interface Emulator (RIE)
      doc-upload:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "9000:8080"
        env_file:
          - .env.local
        depends_on:
          bucket-init:
            condition: service_completed_successfully
        volumes:
          - /tmp/lambda-tmp:/tmp   # PyMuPDF temp files
        healthcheck:
          test:
            - "CMD"
            - "curl"
            - "-s"
            - "-XPOST"
            - "http://localhost:8080/2015-03-31/functions/function/invocations"
            - "-H"
            - "Content-Type: application/json"
            - "-d"
            - |
              {"headers":{"x-api-key":"${var.auth_token}"},"body":"{}"}
          interval: 30s
          timeout: 15s
          retries: 3

    volumes:
      localstack_data:
  COMPOSE
}

##############################################################################
# modules/local/variables.tf
##############################################################################

variable "environment"         { type = string }
variable "name_prefix"         { type = string }
variable "static_bucket_name"  { type = string }
variable "output_bucket_name"  { type = string }
variable "prod_bucket_name"    { type = string }
variable "auth_token"          { type = string; sensitive = true }
variable "openai_api_key"      { type = string; sensitive = true }
variable "pdf_api_key"         { type = string; sensitive = true }
variable "teams_webhook_url"   { type = string; sensitive = true }
variable "fill_pdf_lambda_url" { type = string; default = "" }
variable "backend_url"         { type = string; default = "" }
