"""
JobContext - the single object passed to operations.py for a processing job.

Replaces the flat attribute-bag storage configs (AWSStorageConfig with 30+ attrs,
LocalStorageConfig, etc.). Pre-populated from PathResolver so operations.py gets
the same local_* / dest_* / s3_* interface it expects — zero changes to operations.py.

Construction:
    from src.storage.job_context import JobContext
    from src.storage.paths.resolver import PathResolver
    from src.storage.backends.factory import get_storage_backend

    backend  = get_storage_backend('aws')          # or 'local', 'azure', 'gcp'
    resolver = PathResolver(file_config)
    ctx      = JobContext(backend, resolver, user_id, session_id, pdf_doc_id)

    # Then use exactly like the old config object:
    ctx.local_input_pdf        # /tmp/processing/553_abc_990_input.pdf
    ctx.dest_extracted_json    # s3://bucket/.../extracted.json  (or local path)
    ctx.download_file(src, dst)
    ctx.upload_file(src, dst)
"""

import os
import logging
from uuid import uuid4

logger = logging.getLogger(__name__)


class JobContext:
    """
    Context for one processing job.

    Each instance gets its own isolated processing directory under
    /tmp/processing/<job_id>/ so concurrent requests never share files,
    even when processing the same user/session/pdf_doc_id.

    Attributes mirror the old storage config objects so operations.py
    needs no changes. Paths are generated by PathResolver — no manual
    attribute assignment required.
    """

    def __init__(self, storage_backend, path_resolver, user_id, session_id, pdf_doc_id):
        self._storage = storage_backend
        self._paths   = path_resolver
        self.source_type = storage_backend.source_type

        uid, sid, pid = user_id, session_id, pdf_doc_id

        # Unique directory for this request — prevents concurrent job collisions
        self.processing_dir = os.path.join(
            path_resolver._cfg.get(
                path_resolver._cfg.get_source_type(),
                'processing_dir',
                fallback='/tmp/processing'
            ),
            str(uuid4())
        )
        os.makedirs(self.processing_dir, exist_ok=True)
        logger.debug(f"Job processing dir: {self.processing_dir}")

        local = path_resolver.local_paths(uid, sid, pid, self.processing_dir)

        # ── Local processing paths (/tmp/processing/) ────────────────────
        self.local_input_pdf           = local.get('processing_input_pdf')
        self.local_input_json          = local.get('processing_input_json')
        self.local_global_json         = local.get('processing_input_json')   # alias
        self.local_extracted_json      = local.get('extracted_json')
        self.local_mapped_json         = local.get('mapped_json')
        self.local_radio_json          = local.get('radio_groups_json')
        self.local_embedded_pdf        = local.get('embedded_pdf')
        self.local_filled_pdf          = local.get('filled_pdf')
        self.local_semantic_mapping    = local.get('semantic_mapping')
        self.local_headers_with_fields = local.get('headers_with_fields')
        self.local_final_form_fields   = local.get('final_form_fields')
        self.local_header_file         = local.get('header_file')
        self.local_section_file        = local.get('section_file')
        self.local_llm_predictions     = local.get('llm_predictions')
        self.local_rag_predictions     = local.get('rag_predictions')
        self.local_final_predictions   = local.get('final_predictions')
        self.local_java_mapping        = local.get('java_mapping')
        # Cache registry is a shared constant file in cache/ — not a per-request processing path.
        self.local_cache_registry      = path_resolver.remote_cache_registry(uid, sid, pid)

        # ── Remote source paths (inputs) ─────────────────────────────────
        self.source_input_pdf  = path_resolver.remote_input_pdf(uid, sid, pid)
        self.source_input_json = path_resolver.remote_input_json(uid, sid, pid)

        # AWS-style input aliases (operations.py uses hasattr guards on these)
        self.s3_input_pdf   = self.source_input_pdf
        self.s3_input_json  = self.source_input_json
        self.s3_global_json = self.source_input_json

        # ── Remote destination paths (outputs) ───────────────────────────
        self.dest_extracted_json        = path_resolver.remote_extracted(uid, sid, pid)
        self.dest_mapped_json           = path_resolver.remote_mapped(uid, sid, pid)
        self.dest_radio_json            = path_resolver.remote_radio(uid, sid, pid)
        self.dest_embedded_pdf          = path_resolver.remote_embedded(uid, sid, pid)
        self.dest_filled_pdf            = path_resolver.remote_filled(uid, sid, pid)
        self.dest_semantic_mapping      = path_resolver.remote_semantic_mapping(uid, sid, pid)
        self.dest_headers_with_fields   = path_resolver.remote_headers_with_fields(uid, sid, pid)
        self.dest_final_form_fields     = path_resolver.remote_final_form_fields(uid, sid, pid)
        self.dest_header_file           = path_resolver.remote_header_file(uid, sid, pid)
        self.dest_section_file          = path_resolver.remote_section_file(uid, sid, pid)
        self.dest_java_mapping          = path_resolver.remote_java_mapping(uid, sid, pid)
        self.dest_final_predictions     = path_resolver.remote_final_predictions(uid, sid, pid)
        self.dest_llm_predictions       = path_resolver.remote_llm_predictions(uid, sid, pid)
        self.dest_rag_predictions       = path_resolver.remote_rag_predictions(uid, sid, pid)
        self.dest_cache_registry        = path_resolver.remote_cache_registry(uid, sid, pid)

        # AWS-style output aliases (operations.py accesses these with hasattr guards
        # and also mutates them mid-pipeline — writable attributes, that's fine)
        self.s3_extracted_json  = self.dest_extracted_json
        self.s3_mapped_json     = self.dest_mapped_json
        self.s3_radio_json      = self.dest_radio_json
        self.s3_embedded_pdf    = self.dest_embedded_pdf
        self.s3_filled_pdf      = self.dest_filled_pdf

        # Cache placeholders (inherited from old BaseStorageConfig interface)
        self.cached_embedded_pdf        = None
        self.cached_mapping_json        = None
        self.cached_radio_groups        = None
        self.cached_headers_with_fields = None
        self.cached_final_form_fields   = None
        self.cached_extraction          = None

    # ── Storage delegation ───────────────────────────────────────────────

    def download_file(self, source_path: str, local_path: str) -> str:
        return self._storage.download_file(source_path, local_path)

    def upload_file(self, local_path: str, destination_path: str) -> str:
        return self._storage.upload_file(local_path, destination_path)

    def file_exists(self, file_path: str) -> bool:
        return self._storage.file_exists(file_path)

    def parse_path(self, file_path: str) -> dict:
        return self._storage.parse_path(file_path)

    def __str__(self):
        return f"JobContext(storage={self.source_type})"
