##############################################################################
# modules/local/main.tf
# Local development: generates docker-compose.yml + .env via Terraform
# Spins up LocalStack (S3 mock) + the RAG Lambda container locally
##############################################################################

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# ── Write .env file for local runs ───────────────────────────────────────────

resource "local_file" "env" {
  filename        = "${path.root}/.env.local"
  file_permission = "0600"

  content = <<-ENV
    # ── Generated by Terraform (modules/local) — DO NOT COMMIT ──────────────
    # Environment
    ENVIRONMENT=local

    # S3 (LocalStack)
    S3_BUCKET=${var.rag_bucket_name}
    PROD_BUCKET=${var.prod_bucket_name}
    AWS_DEFAULT_REGION=us-east-1
    AWS_ACCESS_KEY_ID=test
    AWS_SECRET_ACCESS_KEY=test
    AWS_ENDPOINT_URL=http://localstack:4566

    # Lambda self-reference
    RAG_LAMBDA_FUNCTION_NAME=rag-pdf-filler-local

    # Backend
    BACKEND_API_ENDPOINT=${var.backend_api_endpoint}
    BACKEND_AUTH_TOKEN=${var.backend_auth_token}

    # OpenAI
    OPENAI_API_KEY=${var.openai_api_key}
    GPT4_MODEL=${var.gpt4_model}
    GPT4_TEMPERATURE=0.3
    GPT4_MAX_TOKENS=500

    # Embedding
    EMBEDDING_MODEL=sentence-transformer
    ST_MODEL_NAME=${var.st_model_name}

    # Confidence / RAG
    PREDICTION_THRESHOLD=${var.prediction_threshold}
    CONFIDENCE_DECAY_RATE=0.90
    CONFIDENCE_GROWTH_RATE=1.03
    MAX_CONFIDENCE=0.99
    MIN_CONFIDENCE=0.50
    AMBIGUITY_THRESHOLD=0.10
    TOP_K=${var.top_k}
    DEDUP_SIMILARITY_THRESHOLD=0.92

    # Auth
    X_API_KEY=${var.x_api_key}

    # Teams (can be left blank for local; notifier fails silently)
    TEAMS_WEBHOOK_URL=${var.teams_webhook_url}

    # Runtime (match Dockerfile ENV)
    TRANSFORMERS_CACHE=/var/task/model_cache
    HF_HOME=/var/task/model_cache
    TORCH_HOME=/tmp
    MPLCONFIGDIR=/tmp
    PYTHONUNBUFFERED=1
  ENV
}

# ── Write docker-compose.yml ──────────────────────────────────────────────────

resource "local_file" "docker_compose" {
  filename = "${path.root}/docker-compose.local.yml"

  content = <<-COMPOSE
    # Generated by Terraform — local dev environment
    version: "3.9"

    services:
      # ── LocalStack (S3 mock) ─────────────────────────────────────────────
      localstack:
        image: localstack/localstack:3
        ports:
          - "4566:4566"
        environment:
          - SERVICES=s3
          - DEFAULT_REGION=us-east-1
          - AWS_DEFAULT_REGION=us-east-1
        volumes:
          - localstack_data:/var/lib/localstack
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
          interval: 10s
          timeout: 5s
          retries: 5

      # ── Bucket bootstrap (runs once) ─────────────────────────────────────
      bucket-init:
        image: amazon/aws-cli:latest
        depends_on:
          localstack:
            condition: service_healthy
        environment:
          - AWS_ACCESS_KEY_ID=test
          - AWS_SECRET_ACCESS_KEY=test
          - AWS_DEFAULT_REGION=us-east-1
        entrypoint: ["/bin/sh", "-c"]
        command:
          - |
            aws --endpoint-url=http://localstack:4566 s3 mb s3://${var.rag_bucket_name} || true
            aws --endpoint-url=http://localstack:4566 s3 mb s3://${var.prod_bucket_name} || true
            echo "✅ Buckets ready"

      # ── RAG Lambda (local container) ─────────────────────────────────────
      rag-lambda:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "9000:8080"     # Lambda RIE endpoint
        env_file:
          - .env.local
        depends_on:
          bucket-init:
            condition: service_completed_successfully
        volumes:
          - /tmp/rag-model-cache:/var/task/model_cache   # persist model download
        healthcheck:
          test: ["CMD", "curl", "-XPOST", "http://localhost:8080/2015-03-31/functions/function/invocations", "-d", "{\"headers\":{\"x-api-key\":\"${var.x_api_key}\"},\"body\":\"{\\\"api_name\\\":\\\"get_system_info\\\"}\"}"]
          interval: 30s
          timeout: 10s
          retries: 3

    volumes:
      localstack_data:
  COMPOSE
}

##############################################################################
# modules/local/variables.tf
##############################################################################

variable "environment"           { type = string }
variable "name_prefix"           { type = string }
variable "rag_bucket_name"       { type = string }
variable "prod_bucket_name"      { type = string }
variable "openai_api_key"        { type = string; sensitive = true }
variable "x_api_key"             { type = string; sensitive = true }
variable "teams_webhook_url"     { type = string; sensitive = true }
variable "backend_auth_token"    { type = string; sensitive = true; default = "" }
variable "backend_api_endpoint"  { type = string; default = "" }
variable "gpt4_model"            { type = string; default = "gpt-4-turbo-preview" }
variable "st_model_name"         { type = string; default = "all-MiniLM-L6-v2" }
variable "prediction_threshold"  { type = string; default = "0.75" }
variable "top_k"                 { type = string; default = "5" }
